---
- import_playbook: playbook_common.yml

- hosts: all
  become_user: root
  become: true
  vars_files:
    - albus.yml
  tasks:
  # - name: Show some starting info
  #   #remote_user: root
  #   #become_user: root
  #   become: true
  #   command: whoami
  #   register: hello

  # - debug: msg="{{ hello.stdout }}"
  # - debug: msg="{{ hello.stderr }}"


  # Create working folders and symlinks
  - file:
      path: /opt/albus/pharo
      state: directory
      mode: 0755
      owner: 'ubuntu'
      group: 'ubuntu'
  - file:
      path: /opt/albus/pharo/main
      src: /opt/albus/main
      state: link
      owner: 'ubuntu'
      group: 'ubuntu'
  
  - name: Add apt architecture i386 for pharo
    shell: /usr/bin/dpkg --add-architecture i386 && apt-get update
  
  # TODO: Oben reinnehmen sobald Ansible diesen Bug released hat: https://github.com/ansible/ansible/pull/24703
  - name: Install basic apt packages i386 by hand
    shell: "apt-get install {{item}} -y"
    with_items:
    - libc6:i386
    - zlib1g:i386
    - libncurses5:i386
    - libbz2-1.0:i386
    - libssl1.0.0:i386
    - libX11.6:i386
    - libGL.1:i386
    - libasound2:i386


    
  #
  # PHARO SMALLTALK
  #
  - name: Download pharo smalltalk
    become_user: ubuntu
    # become: true
#    shell: curl get.pharo.org/50+vm | bash && mv Pharo.image albus.image && mv Pharo.changes albus.changes
    shell: curl get.pharo.org/64/61+vmT | bash && mv Pharo.image albus.image && mv Pharo.changes albus.changes
    args:
      chdir: /opt/albus/pharo
      creates: /opt/albus/pharo/albus.image
      warn: no


  #
  # ALBUS
  #
  - name: Install Albus code in pharo image
    become_user: ubuntu
    # become: true
    shell: /opt/albus/pharo/pharo albus.image --no-default-preferences st /opt/albus/install/installAlbus.st && touch albusIsInstalled
    args:
      chdir: /opt/albus/pharo
      creates: /opt/albus/pharo/albusIsInstalled
  - name: Running Albus
    shell: monit reload && sleep 2 && monit start albus_pharo
    # unless => '/usr/bin/pgrep pharo',
    
