---
- include: playbook_common.yml

- hosts: all
  become_user: root
  become: true
  vars_files:
    - albus.yml
  tasks:
  # - name: Show some starting info
  #   #remote_user: root
  #   #become_user: root
  #   become: true
  #   command: whoami
  #   register: hello

  # - debug: msg="{{ hello.stdout }}"
  # - debug: msg="{{ hello.stderr }}"


  #
  # PHARO SMALLTALK
  #
  - name: Download pharo smalltalk
    become_user: ubuntu
    # become: true
    shell: curl get.pharo.org/50+vm | bash && mv Pharo.image albus.image && mv Pharo.changes albus.changes
    args:
      chdir: /opt/albus/pharo
      creates: /opt/albus/pharo/albus.image
      warn: no


  #
  # ALBUS
  #
  - name: Install Albus code in pharo image
    become_user: ubuntu
    # become: true
    shell: /opt/albus/pharo/pharo albus.image --no-default-preferences st /opt/albus/install/installAlbus.st && touch albusIsInstalled
    args:
      chdir: /opt/albus/pharo
      creates: /opt/albus/pharo/albusIsInstalled
  - name: Running Albus
    shell: monit reload && sleep 2 && monit start albus_pharo
    # unless => '/usr/bin/pgrep pharo',
    
