#!/bin/bash

# Produktives Albus stoppen
monit stop albus_pharo

echo "Warte auf Albus Ende (Kann Minuten dauern) ..."

# Warten bis pharo Prozesse beendet
while pgrep pharo  > /dev/null; do sleep 1; echo -n "."; done
